# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
# config/packages/scheb_2fa.yaml
    email:
        digits: 6
        enabled: true
        sender_email: no-reply@libairthe.com
        sender_name: Libairthé
#        mailer: acme.custom_mailer_service  # Use alternative service to send the authentication code
#        code_generator: acme.custom_code_generator_service  # Use alternative service to generate authentication code
        template: security/2fa_form.html.twig
